runtime: python39

instance_class: F1

env_variables:
  STREAMLIT_SERVER_PORT: 8080
  STREAMLIT_SERVER_HEADLESS: true
  STREAMLIT_SERVER_ENABLE_CORS: false
  STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION: true

entrypoint: streamlit run app.py --server.port=8080 --server.address=0.0.0.0

automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic